In [3]:
import pandas as pd
import requests
import json

In [10]:
# Base URL for the API call
base_url = "https://api.worldbank.org/v2/country/no;nz;dk;se;fi/indicator/NY.GDP.PCAP.PP.CD"

# Parameters for the API call
params = {
    "date": "2000:2023",
    "format": "json"
}
response = requests.get(base_url, params=params)
response = response.json()
response[0]['pages']

3

In [11]:
# Base URL for the API call
base_url = "https://api.worldbank.org/v2/country/no;nz;dk;se;fi/indicator/NY.GDP.PCAP.PP.CD"

# Parameters for the API call
params = {
    "date": "2000:2023",
    "format": "json",
    "page": 1  # Start with the first page
}

# Number of pages
num_pages = response[0]['pages']

# Create an empty list to store the data for each page
all_data = []

# Loop through all the pages
for page in range(1, num_pages + 1):
    # Update the page number in the parameters
    params["page"] = page

    # Make the API call
    response = requests.get(base_url, params=params)

    # Check if the request was successful
    if response.status_code == 200:
        # Process the data for the current page
        data = response.json()
        
        # Extract the relevant data from the response
        all_data.extend(data[1])  # Assuming the data is in the second element of the JSON response

    else:
        print(f"Error: {response.status_code}")

# Create a DataFrame from the combined data
df = pd.DataFrame(all_data)

# Print the DataFrame
print(df)

                                             indicator  \
0    {'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...
1    {'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...
2    {'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...
3    {'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...
4    {'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...
..                                                 ...
115  {'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...
116  {'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...
117  {'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...
118  {'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...
119  {'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...

                              country countryiso3code  date         value  \
0    {'id': 'DK', 'value': 'Denmark'}             DNK  2023  76687.902844
1    {'id': 'DK', 'value': 'Denmark'}             DNK  2022  77953.678661
2    {'id': 'DK', 'value': 'Denmark'}             DNK  2021  69878.934812
3    {'id': 'DK', 'value': 'Denmark'}             DNK  2020  62529.251057
4    {'id': 'DK', 'value': 'Denmark'}             DNK  2019  60787.463358
..                                ...             ...   ...           ...
115   {'id': 'SE', 'value': 'Sweden'}             SWE  2004  33859.573190
116   {'id': 'SE', 'value': 'Sweden'}             SWE  2003  31816.621040
117   {'id': 'SE', 'value': 'Sweden'}             SWE  2002  30926.505599
118   {'id': 'SE', 'value': 'Sweden'}             SWE  2001  29936.445656
119   {'id': 'SE', 'value': 'Sweden'}             SWE  2000  29622.038475

    unit obs_status  decimal
0                          1
1                          1
2                          1
3                          1
4                          1
..   ...        ...      ...
115                        1
116                        1
117                        1
118                        1
119                        1

[120 rows x 8 columns]

In [12]:
df

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...","{'id': 'DK', 'value': 'Denmark'}",DNK,2023,76687.902844,,,1
1,"{'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...","{'id': 'DK', 'value': 'Denmark'}",DNK,2022,77953.678661,,,1
2,"{'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...","{'id': 'DK', 'value': 'Denmark'}",DNK,2021,69878.934812,,,1
3,"{'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...","{'id': 'DK', 'value': 'Denmark'}",DNK,2020,62529.251057,,,1
4,"{'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...","{'id': 'DK', 'value': 'Denmark'}",DNK,2019,60787.463358,,,1
...,...,...,...,...,...,...,...,...
115,"{'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...","{'id': 'SE', 'value': 'Sweden'}",SWE,2004,33859.573190,,,1
116,"{'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...","{'id': 'SE', 'value': 'Sweden'}",SWE,2003,31816.621040,,,1
117,"{'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...","{'id': 'SE', 'value': 'Sweden'}",SWE,2002,30926.505599,,,1
118,"{'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...","{'id': 'SE', 'value': 'Sweden'}",SWE,2001,29936.445656,,,1
119,"{'id': 'NY.GDP.PCAP.PP.CD', 'value': 'GDP per ...","{'id': 'SE', 'value': 'Sweden'}",SWE,2000,29622.038475,,,1

In [ ]:
# property price
interest_pm = interest_rate.merge(pm_m, left_on=['Country', 'Year'], right_on=['Country Name', 'Year'])
interest_pm = interest_pm.drop(columns=['Country Name'])
gdp_interest_pm = interest_pm.merge(GDP_M, left_on=['Country', 'Year'], right_on=['Country Name', 'Year']).drop(columns=['Country Name'])
final_format = gdp_interest_pm.merge(inflation_unemployment,left_on=['Country', 'Year' ], right_on=['Country', 'Year'])
# final_format = final_format.merge(HPI,on=['Country', 'Year'])
# final_format = final_format.merge(urban_data,left_on=['Country', 'Year'], right_on=['Country Name', 'Year']).drop(columns=['Country Name'])
# final_format = final_format.merge(debt,on=['Country','Year'])
# final_format = final_format.merge(rent_price_filtered,on=['Country','Year'])
# final_format